### ISSUE TITLE
[Bug] npm Java dependency too old, fails on npm install

### ISSUE THREAD

**Issue by Luchillo** [agmoyano/node-jasper#21]
The java package itself fails to install due to the dependency being too old:
```sh
Current version: ^0.4.2
Latest version: 0.7.0
```

**Comment by brunnobb** [comment]
This is a know bug.. There are many branches with this fixed.. 
The repository manager is not actually looking this project, and the fix commits does not get merged.. 

Clone one of the branches and try again

**Comment by Luchillo** [comment]
@brunnobb A few minutes ago @agmoyano updated the dependencies, however the errors still arise like this:
```sh
> java@0.6.1 install /Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/java
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/java
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN jasper@1.0.0 No description
npm WARN jasper@1.0.0 No repository field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "agmoyano/node-jasper"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.6.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aplicacionesosgroup/Documents/Tests/jasper/npm-debug.log
```

**Comment by Luchillo** [comment]
@brunnobb Tried your fork and same issue, as good as both of you use the java package under 0.7.0 this error will keep poping out.

**Comment by agmoyano** [comment]
Thanks for reporting. I just updated java version to 0.7.0.
