### ISSUE TITLE
[Bug] loadClassSync class not found

### ISSUE THREAD

**Issue by luchillo17** [agmoyano/node-jasper#22]
After the update to npm Java 0.7.0 this lib installs ok, but when running the basic example of the README this is the error:

``` sh
/Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/node-jasper/index.js:151
                cl.loadClassSync(options.drivers[i].class).newInstanceSync();
                   ^

Error: Error running instance method
java.lang.ClassNotFoundException: org.posgresql.Driver
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

    at Error (native)
    at Array.async.auto.loadClass (/Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/node-jasper/index.js:151:8)
    at listener (/Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/async/lib/async.js:490:46)
    at /Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/async/lib/async.js:441:17
    at _each (/Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Users/aplicacionesosgroup/Documents/Tests/jasper/node_modules/async/lib/async.js:440:13)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by agmoyano** [comment]
Hi, please check the path to your jdbc driver jar

**Comment by Luchillo** [comment]
I checked and it is in the expected folder, in `lib` side to side with the `jasperreports` lib, btw does it needs an specific version? i'm using:
1. jasperreports-5.6.0
2. postgresql-9.2-1004.jdbc41.jar

**Comment by Luchillo** [comment]
I tried with the example inside `json_example` which should output a pdf, it tries to process it, but after opening some kind of binary of java without window it just freezes forcing me to stop the command with `ctrl + c`.

**Comment by thanhnha0706** [comment]
@Luchillo I have this issue as well on macOS 10.12. I don't know what's wrong with it.

**Comment by Luchillo** [comment]
Nope, we grabbed another lib, sorry.

**Comment by thanhnha0706** [comment]
@Luchillo Can you please tell me which lib you're using? Thank you very much!

**Comment by welintonti** [comment]
Hello guys,
@luchillo17  your paramenter class `org.posgresql.Driver` is wrong. The word **posgresql** is missing **t**.  The correct is: `org.postgresql.Driver`

@thanhnha0706 This may be useful for you.

@agmoyano  I created a pull request, correcting the call in the README https://github.com/agmoyano/node-jasper/pull/31
