### ISSUE TITLE
How to send data to Jasper Report using Node js?

### ISSUE THREAD

**Issue by rangaKES** [agmoyano/node-jasper#50]
Hi Agmoyano,

I'm new to Jasper Reports and trying to connect jasper reports with my node js (express) application.
For that, I have tried your node-jasper node module & unfortunately, I'm unable to send data to jasper report because I couldn't understand how that mechanism works.

I'll tell you what I have done in brief.
1) First of all, I installed your node-jasper module to my express project.
2) Then I did everything as you have described in your node-jasper Github page. I'm using the Progress OpenEdge database with JDBC. (I have no issue getting data from database)
3) For creating the Jasper report I used Jasper Studio. By using that I have created employees.jrxml file and added that to the reports directory.
4) But after starting the server, I got two errors calling that lib and dist folders are missing inside of the jasperreports-6.10.0 library that I have downloaded and put in the express project directory.
5) Then I have created those two folders. Then I got an error called some jar files missing.
6) For that, I downloaded all jar files for jasper reports version 6.10.0 from 'https://jar-download.com/artifacts/net.sf.jasperreports/jasperreports/6.10.0' website and put all those jar files in both lib and dist folders that I have created.
7) Then that error was gone.
8) But after I'm going to call '/pdf' rest endpoint, the report is created as employee.pdf but without any data. It's only an empty pdf without any content.

Can you help me on how to send data to the jasper report and how to get a pdf output with all contents?

Another question that I have to ask you is, can we do SQL queries inside of the report object as described below instead of calling a dataset?

expressApp.get('/pdf', function(req, res, next) {

    var report = {
        report: 'employee',
        data: {
            // id: parseInt(req.query.id, 10),
	-------- do a sql query to get data instead of passing json object ----------------------
            secundaryDataset: jasper.toJsonDataSource({
                data: [{ emp_name: "ABCD", nic: "V123456789" }] 
            }, 'data')
        },

	--------- do a sql query to get dataset instead of passing json object ------------------
        dataset: [
            {
                emp_name: "ABCD",
                nic: "V123456789"
            },
            {
                emp_name: "EFGH",
                nic: "V987654321"
            }
        ]
    }

    var pdf = jasper.pdf(report);

    res.set({
        'Content-type': 'application/pdf',
        'Content-Length': pdf.length
    });
    res.send(pdf);
});

Also, what type of outputs can we generate by using node-jasper node module? (Ex: - pdf, csv, etc.)

I have attached my index.js file as index_js.txt, employee.jrxml file as employee_jrxml.txt and some screenshots of the project directory structure. 

Thank You!

[index_js.txt](https://github.com/agmoyano/node-jasper/files/4642330/index_js.txt)

[employee_jrxml.txt](https://github.com/agmoyano/node-jasper/files/4642339/employee_jrxml.txt)

![downloaded and added jar files in dist folder](https://user-images.githubusercontent.com/54706531/82175966-036a6280-98f3-11ea-958b-b059de58aa13.jpg)

![downloaded and added jar files in lib folder](https://user-images.githubusercontent.com/54706531/82175972-05342600-98f3-11ea-86bb-52a4ca470a4e.jpg)

![lib and dist folders in jasperreport-6 10 0 library](https://user-images.githubusercontent.com/54706531/82175975-06655300-98f3-11ea-9e3d-99795e70559c.jpg)

![project structure](https://user-images.githubusercontent.com/54706531/82175976-06fde980-98f3-11ea-93f3-873c87c28da0.jpg)

**Comment by agmoyano** [comment]
Hi @rangaKES,

You should use the "project" version of jasper library.

You can get it here
https://community.jaspersoft.com/project/jasperreports-library/releases

Search for the jasperreports-<desired version>-project.zip and download.

Now that you've got the correct version, please try again.

Hope it helps.

**Comment by rangaKES** [comment]
Hi @agmoyano,

Thank you for your immediate reply. I have tried your solution. But still I have following error occurring when I'm calling '/pdf' endpoint. Can you please provide a solution for that? Also If possible, can you share a sample project code on how to use node-jasper module?

`Error: Error running static method
java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:173)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:131)
        at net.sf.jasperreports.functions.FunctionsBundle.addFunctionClass(FunctionsBundle.java:83)
        at net.sf.jasperreports.functions.FunctionsBundle.<init>(FunctionsBundle.java:53)
        at net.sf.jasperreports.functions.FunctionsRegistryFactory.createRegistry(FunctionsRegistryFactory.java:73)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:299)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:274)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:194)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:157)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:129)
        at net.sf.jasperreports.engine.DefaultJasperReportsContext.getExtensions(DefaultJasperReportsContext.java:277)
        at net.sf.jasperreports.engine.component.ComponentsEnvironment.findBundles(ComponentsEnvironment.java:111)
        at net.sf.jasperreports.engine.component.ComponentsEnvironment.getCachedBundles(ComponentsEnvironment.java:101)
        at net.sf.jasperreports.engine.component.ComponentsEnvironment.getBundles(ComponentsEnvironment.java:89)
        at net.sf.jasperreports.engine.xml.JRReportSaxParserFactory.getSchemaLocations(JRReportSaxParserFactory.java:103)
        at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.configureParser(BaseSaxParserFactory.java:163)
        at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.createParser(BaseSaxParserFactory.java:118)
        at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createParser(JRXmlDigesterFactory.java:1598)
        at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createDigester(JRXmlDigesterFactory.java:1567)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:263)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:219)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:194)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:185)
        at net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:254)
        at net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(JasperCompileManager.java:555)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePartial
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 31 more

    at jasper.compileSync (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:386:10)
    at D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:321:23
    at Array.forEach (<anonymous>)
    at jasper.export (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:319:10)
    at jasper.pdf (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:212:21)
    at D:\Jasper_Test\Backend\Node_Jasper\Backend\index.js:63:22
    at Layer.handle [as handle_request] (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\layer.js:95:5)
`

Thank You!

**Comment by agmoyano** [comment]
Hello @rangaKES, seems you are using the class org/joda/time/ReadablePartial inside your report. If you've got the jar file for it, then you could place it with the other jars inside the decompressed jasperreports project directory.

Cheers.

**Comment by Clifte** [comment]
The lib folder is not found in this version of Jasperreports lib **6.12.2** either the tar.gz and zip 
https://ufpr.dl.sourceforge.net/project/jasperreports/jasperreports/JasperReports%206.12.2/jasperreports-6.12.2-project.tar.gz

**Comment by agmoyano** [comment]
Hmm.. weird.. seems you grabbed a copy of the project that is not
compiled.. it has a build.xml for ant building and a pom.xml for maven..

I'd really suggest you download from
https://community.jaspersoft.com/project/jasperreports-library/releases even
if having to register to download is tiresome.

Please, let me know if that helps.

**Comment by rangaKES** [comment]
Hi @agmoyano,

I have tried your solution above by downloading and placing jasperreports-6.12.2 (from https://community.jaspersoft.com/project/jasperreports-library/releases) in my project. But in there also I had to create two folders called 'lib' and 'dist'. And finally when all the errors gone, I called my '/pdf' endpoint and it's giving following error.

`Error: Error running static method
java.lang.NoClassDefFoundError: org/springframework/beans/factory/support/BeanDefinitionRegistry
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:173)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:131)
        at net.sf.jasperreports.engine.util.ClassUtils.instantiateClass(ClassUtils.java:60)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:298)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:274)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:194)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:157)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:129)
        at net.sf.jasperreports.engine.DefaultJasperReportsContext.getExtensions(DefaultJasperReportsContext.java:277)
        at net.sf.jasperreports.engine.component.ComponentsEnvironment.findBundles(ComponentsEnvironment.java:111)
        at net.sf.jasperreports.engine.component.ComponentsEnvironment.getCachedBundles(ComponentsEnvironment.java:101)
        at net.sf.jasperreports.engine.component.ComponentsEnvironment.getBundles(ComponentsEnvironment.java:89)
        at net.sf.jasperreports.engine.xml.JRReportSaxParserFactory.getSchemaLocations(JRReportSaxParserFactory.java:103)
        at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.configureParser(BaseSaxParserFactory.java:163)
        at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.createParser(BaseSaxParserFactory.java:118)
        at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createParser(JRXmlDigesterFactory.java:1598)
        at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createDigester(JRXmlDigesterFactory.java:1567)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:264)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:220)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:195)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:186)
        at net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:254)
        at net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(JasperCompileManager.java:555)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.support.BeanDefinitionRegistry
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 29 more

    at jasper.compileSync (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:386:10)
    at D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:321:23
    at Array.forEach (<anonymous>)
    at jasper.export (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:319:10)
    at jasper.pdf (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\node-jasper\index.js:212:21)
    at D:\Jasper_Test\Backend\Node_Jasper\Backend\index.js:63:22
    at Layer.handle [as handle_request] (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Jasper_Test\Backend\Node_Jasper\Backend\node_modules\express\lib\router\layer.js:95:5)`

Can you please check this and give me a solution?

Thank You!

**Comment by rangaKES** [comment]
Hi @Clifte,

I don't know whether I'm correctly understand what you have mentioned. But in my project, I created those two folders 'lib' and 'dist' inside of the jasperreports-6.12.2 by myself.

Thank You!

**Comment by Winsgton** [comment]
I also have the same problem and I couldn't solve it.
In jasperstudio it compiles and presents the report, but when I make the request, it shows this error Error running static method\nnet.sf.jasperreports.engine.JRException: Class not found when loading object from file.

If anyone knows and can help, I'd appreciate it!

**Comment by rennan0** [comment]
> I also have the same problem and I couldn't solve it. In jasperstudio it compiles and presents the report, but when I make the request, it shows this error Error running static method\nnet.sf.jasperreports.engine.JRException: Class not found when loading object from file.
> 
> If anyone knows and can help, I'd appreciate it!

I had the same issue and I managed to solve it by downloading the jar dependencies from https://jar-download.com/artifacts/net.sf.jasperreports/jasperreports/6.20.0. 
Inside my lib folder jasperreports-6.2.0, I created two new folders: dist and lib and put the contents of the downloaded dependencies inside them
