### ISSUE TITLE
Error: Could not create class net.sf.jasperreports.engine.JREmptyDataSource

### ISSUE THREAD

**Issue by CristianAlvarado82** [agmoyano/node-jasper#55]
Hi, please need solution por this issues, tray varios structs but no solve problem, I need one estructure complet of proyect for exeute this node-jsaper please

var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.
                   ^

Error: Could not create class net.sf.jasperreports.engine.JREmptyDataSource
java.lang.NoClassDefFoundError: net/sf/jasperreports/engine/JREmptyDataSource
Caused by: java.lang.ClassNotFoundException: net.sf.jasperreports.engine.JREmptyDataSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

    at Java.java.import (C:\Users\Cristian Alvarado\Desktop\node-jasper-master\node_modules\java\lib\nodeJavaBridge.js:227:20)
    at Array.async.auto.imports (C:\Users\Cristian Alvarado\Desktop\node-jasper-master\node_modules\node-jasper\index.js:176:28)
    at listener (C:\Users\Cristian Alvarado\Desktop\node-jasper-master\node_modules\async\lib\async.js:490:46)
    at C:\Users\Cristian Alvarado\Desktop\node-jasper-master\node_modules\async\lib\async.js:441:17
    at _each (C:\Users\Cristian Alvarado\Desktop\node-jasper-master\node_modules\async\lib\async.js:46:13)
    at Immediate.taskComplete (C:\Users\Cristian Alvarado\Desktop\node-jasper-master\node_modules\async\lib\async.js:440:13)
    at processImmediate (internal/timers.js:456:21) {
  cause: nodeJava_java_lang_NoClassDefFoundError {}

**Comment by dcsline** [comment]
Have you tested node-jasper with simple report? If not do it.
