### ISSUE TITLE
Error: Could not create class net.sf.jasperreports.engine.data.JsonDataSource

### ISSUE THREAD

**Issue by SrilakshmiGodugunuri27** [agmoyano/node-jasper#57]

**Comment by sirhennig** [comment]
samme problem here, seems like it can't find a class it is searching for

var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.
                   ^
Error: Could not create class net.sf.jasperreports.engine.JREmptyDataSource
java.lang.NoClassDefFoundError: net/sf/jasperreports/engine/JREmptyDataSource
Caused by: java.lang.ClassNotFoundException: net.sf.jasperreports.engine.JREmptyDataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Comment by dcsline** [comment]
This is my tested content for sample.js 👍

**Comment by dcsline** [comment]
var fs = require('fs');

var jasper = require('node-jasper')({
    path: '../lib/jasperreports-5.6.0',
    reports: {
        stock_ofertas: {
            jasper: __dirname + '/sample.jasper',
            jrxml: __dirname + '/sample.jrxml',
            conn: 'in_memory_json'
        }
    }
});

jasper.ready(function() {
    var r = jasper.export(
        {
            report: 'stock_ofertas',
            data: {
                language: 'spanish',
                // on jasper make a parameter named "dataset2" and use on a subreport:
                // ((net.sf.jasperreports.engine.data.JsonDataSource)$P{dataset2})
                dataset2: jasper.toJsonDataSource(
                    {
                        dados: [{ value: 1, value: 2 }]
                    },
                    'dados'
                )
            },
            dataset: [
                {
                    name: 'Gonzalo',
                    lastname: 'Vinas' // TODO: check on UTF-8
                },
                {
                    name: 'Agustin',
                    lastname: 'Moyano'
                }
            ]
        },
        'pdf'
    );

    //fs.writeFile(__dirname + '/sample.pdf', r);
    fs.writeFile(__dirname+ '/sample.pdf', r, (error)=>{
        if(error) console.log(error);
    })
});

**Comment by leftundersun** [comment]
To make it works, I needed to move the lib folder from dist to root. Sometimes he complains about fonts, but i just changed all to some that works and it goes fine.
