### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/beanutils/locale/LocaleConverter

### ISSUE THREAD

**Issue by jdd0702** [agmoyano/node-jasper#63]
Hi @agmoyano,

I'm trying to run a report based on the node js json data you have but I'm encountering this error.
I have tried to follow the setup you have. I'm I missing something on this?

Thank you in advance.

```
var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.
                   ^

Error: Could not create class net.sf.jasperreports.engine.data.JsonDataSource
java.lang.NoClassDefFoundError: org/apache/commons/beanutils/locale/LocaleConverter
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.locale.LocaleConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

    at Java.java.import (/home/mythra/Documents/workspace/NodeJS/jasperserver/node_modules/java/lib/nodeJavaBridge.js:227:20)
    at Array.async.auto.imports (/home/mythra/Documents/workspace/NodeJS/jasperserver/node_modules/node-jasper/index.js:177:31)
    at listener (/home/mythra/Documents/workspace/NodeJS/jasperserver/node_modules/async/lib/async.js:490:46)
    at /home/mythra/Documents/workspace/NodeJS/jasperserver/node_modules/async/lib/async.js:441:17
    at _each (/home/mythra/Documents/workspace/NodeJS/jasperserver/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/home/mythra/Documents/workspace/NodeJS/jasperserver/node_modules/async/lib/async.js:440:13)
    at processImmediate (internal/timers.js:464:21) {
  cause: nodeJava_java_lang_NoClassDefFoundError {}
}
```

**Comment by DavidHequet** [comment]
Had same issue, i user the provided jasper lib and dependancy from this unofficial fork : 

https://github.com/beeattack/node-jasper-th
