### ISSUE TITLE
Error: libjvm.so ISSUE

### ISSUE THREAD

**Issue by anz000** [agmoyano/node-jasper#7]
Cannot setup Jasper reports in my installation. I have java installed and set JAVA_HOME. Setting LD_LIBRARY_PATH leads to a Segmentation Fault. Please help! This is the error message in my terminal.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libjvm.so: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/node-jasper/node_modules/java/lib/nodeJavaBridge.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by agmoyano** [comment]
Hi @anz000 which OS are you running and how did you installed Java?

**Comment by anz000** [comment]
I am using Ubuntu 14.10, and I installed openjdk-7 via. apt-get. I have actually found the solution . I hope it helps somebody, and for future reference:

One needs to put the Java path in /etc/ld.so.conf.d/randomLibs.conf
Mine was:
/usr/lib/jvm/java-7-openjdk-amd64/
/usr/lib/jvm/java-7-openjdk-amd64/bin
/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64
/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server

**Comment by agmoyano** [comment]
Ok, glad you nailed it!

**Comment by girirajsharma** [comment]
It doesn't works in my case although issue is exactly the same.

**Comment by agmoyano** [comment]
Hi, this is a [node-java](https://github.com/joeferner/node-java) issue. Have you tried looking for the answer there? or have you tried @anz000 fix?

Cheers.
