### ISSUE TITLE
Error while installing node-jasper

### ISSUE THREAD

**Issue by Canzervero** [agmoyano/node-jasper#78]
Hi,

I have a problem installing node-jasper:

`emoreno@serbero:~/Projects/GitHub/jasper-node$ npm install node-jasper
npm ERR! code 1
npm ERR! path /home/emoreno/Projects/GitHub/jasper-node/node_modules/java
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@14.21.3 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/emoreno/Projects/GitHub/jasper-node/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/emoreno/Projects/GitHub/jasper-node/node_modules/java/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/emoreno/Projects/GitHub/jasper-node/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/emoreno/.cache/node-gyp/14.21.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/emoreno/.cache/node-gyp/14.21.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/emoreno/Projects/GitHub/jasper-node/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/emoreno/.cache/node-gyp/14.21.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/emoreno/Projects/GitHub/jasper-node/node_modules/java',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/emoreno/Projects/GitHub/jasper-node/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/emoreno/Projects/GitHub/jasper-node/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/emoreno/Projects/GitHub/jasper-node/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/emoreno/Projects/GitHub/jasper-node/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/emoreno/Projects/GitHub/jasper-node/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/emoreno/Projects/GitHub/jasper-node/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/emoreno/Projects/GitHub/jasper-node/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/emoreno/Projects/GitHub/jasper-node/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.19.0-40-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/home/emoreno/Projects/GitHub/jasper-node/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/emoreno/Projects/GitHub/jasper-node/node_modules/java
npm ERR! gyp ERR! node -v v14.21.3
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /home/emoreno/.npm/_logs/2023-04-22T22_24_44_587Z-debug-0.log`

ENVIRONMENT:

SO: Ubuntu 22.04.2 LTS
Node: v14.21.3
Python: 2.7.18 and 3.10.6

Do you any idea to solve the problem?

Thanks!

**Comment by MardonisAlves** [comment]
I have this same error
